// ============================================================
// Dynamic Taxonomy Operations
// ============================================================
// Manages reading and writing of dynamic taxonomy (segments + categories)
// generated by the DynamicClassifier during reclassification.

import { v4 as uuidv4 } from 'uuid';
import { getDatabase } from './connection.js';
import { withTransaction } from './transaction.js';

export interface TaxonomySegment {
  code: string;
  label: string;
  description: string;
}

export interface TaxonomyCategory {
  segmentCode: string;
  code: string;
  label: string;
  description: string;
}

export interface DynamicTaxonomy {
  segments: TaxonomySegment[];
  categories: TaxonomyCategory[];
}

const SEGMENT_COLOR_PALETTE = ['#FF6B6B', '#4ECDC4', '#45B7D1', '#FFA07A', '#98D8C8', '#DDA0DD', '#87CEEB', '#F0E68C'];

/**
 * Clear and repopulate segments + categories tables with a new taxonomy.
 * Runs in a transaction. Does NOT touch content_types (static).
 */
export function replaceTaxonomy(taxonomy: DynamicTaxonomy): void {
  withTransaction(() => {
    const db = getDatabase();

    // Clear existing taxonomy data
    db.prepare('DELETE FROM categories').run();
    db.prepare('DELETE FROM segments').run();

    // Insert new segments
    const segStmt = db.prepare(
      'INSERT INTO segments (id, name, code, description, color, created_at) VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP)'
    );
    for (let i = 0; i < taxonomy.segments.length; i++) {
      const seg = taxonomy.segments[i];
      const color = SEGMENT_COLOR_PALETTE[i % SEGMENT_COLOR_PALETTE.length];
      segStmt.run(uuidv4(), seg.label, seg.code, seg.description, color);
    }

    // Insert new categories
    const catStmt = db.prepare(
      'INSERT INTO categories (segment_code, category_code, display_name, description, created_at) VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)'
    );
    for (const cat of taxonomy.categories) {
      catStmt.run(cat.segmentCode, cat.code, cat.label, cat.description);
    }
  });
}

/**
 * Read current segment labels from DB.
 * Returns Record<code, label> (e.g., { A: 'AI & Machine Learning' })
 * Falls back to hardcoded defaults if DB is empty.
 */
export function getSegmentLabels(): Record<string, string> {
  const db = getDatabase();
  const rows = db.prepare('SELECT code, name FROM segments').all() as Array<{ code: string; name: string }>;

  if (rows.length === 0) {
    return DEFAULT_SEGMENT_LABELS;
  }

  // Check if codes are single-letter format (dynamic taxonomy) vs old multi-char format
  const hasSingleLetterCodes = rows.some(r => r.code.length === 1);
  if (!hasSingleLetterCodes) {
    // Old-format codes (AI_ML, DEV_TOOLS) — fall back to defaults
    return DEFAULT_SEGMENT_LABELS;
  }

  const labels: Record<string, string> = {};
  for (const row of rows) {
    labels[row.code] = row.name;
  }
  return labels;
}

/**
 * Read current category labels from DB.
 * Returns Record<segmentCode, Record<categoryCode, label>>
 * Falls back to hardcoded defaults if DB is empty.
 */
export function getCategoryLabels(): Record<string, Record<string, string>> {
  const db = getDatabase();
  const rows = db.prepare('SELECT segment_code, category_code, display_name FROM categories').all() as Array<{
    segment_code: string;
    category_code: string;
    display_name: string;
  }>;

  if (rows.length === 0) {
    return DEFAULT_CATEGORY_LABELS;
  }

  const labels: Record<string, Record<string, string>> = {};
  for (const row of rows) {
    if (!labels[row.segment_code]) {
      labels[row.segment_code] = {};
    }
    labels[row.segment_code][row.category_code] = row.display_name;
  }
  return labels;
}

// ============================================================
// Hardcoded fallbacks (used when DB tables are empty)
// ============================================================

const DEFAULT_SEGMENT_LABELS: Record<string, string> = {
  A: 'AI & Machine Learning',
  T: 'Technology & Development',
  F: 'Finance & Economics',
  S: 'Sports & Fitness',
  H: 'Health & Wellness',
  B: 'Business & Productivity',
  E: 'Entertainment & Media',
  L: 'Lifestyle & Personal',
  X: 'Science & Research',
  C: 'Creative & Design',
};

const DEFAULT_CATEGORY_LABELS: Record<string, Record<string, string>> = {
  A: { LLM: 'Large Language Models', AGT: 'AI Agents', FND: 'Foundation Models', MLO: 'MLOps', NLP: 'Natural Language Processing', CVS: 'Computer Vision', GEN: 'Generative AI', ETH: 'AI Ethics', RES: 'AI Research', OTH: 'Other AI' },
  T: { WEB: 'Web Development', MOB: 'Mobile Development', DEV: 'Developer Tools', CLD: 'Cloud & Infrastructure', SEC: 'Security', DAT: 'Data Engineering', API: 'APIs & Integrations', OPS: 'DevOps', HRD: 'Hardware', OTH: 'Other Tech' },
  F: { INV: 'Investing', CRY: 'Crypto & Blockchain', FPA: 'FP&A', BNK: 'Banking', TAX: 'Tax & Accounting', PFN: 'Personal Finance', MKT: 'Markets', REL: 'Real Estate', ECN: 'Economics', OTH: 'Other Finance' },
  S: { NFL: 'NFL Football', FAN: 'Fantasy Sports', FIT: 'Fitness', RUN: 'Running', GYM: 'Gym & Training', NBA: 'Basketball', MLB: 'Baseball', SOC: 'Soccer', OLY: 'Olympics', OTH: 'Other Sports' },
  H: { MED: 'Medical', MNT: 'Mental Health', NUT: 'Nutrition', SLP: 'Sleep', ACC: 'Accessibility', WEL: 'Wellness', FRT: 'Fertility', AGE: 'Aging', DIS: 'Disease', OTH: 'Other Health' },
  B: { STR: 'Strategy', MNG: 'Management', PRD: 'Product', MKT: 'Marketing', SAL: 'Sales', OPS: 'Operations', HRS: 'HR & People', STP: 'Startups', ENT: 'Enterprise', OTH: 'Other Business' },
  E: { GAM: 'Gaming', MUS: 'Music', MOV: 'Movies & TV', STR: 'Streaming', SOC: 'Social Media', POP: 'Pop Culture', POD: 'Podcasts', CEL: 'Celebrities', EVT: 'Events', OTH: 'Other Entertainment' },
  L: { HOM: 'Home', FAS: 'Fashion', FOD: 'Food & Cooking', TRV: 'Travel', REL: 'Relationships', PAR: 'Parenting', PET: 'Pets', HOB: 'Hobbies', GAR: 'Garden', OTH: 'Other Lifestyle' },
  X: { PHY: 'Physics', BIO: 'Biology', CHM: 'Chemistry', AST: 'Astronomy', ENV: 'Environment', MAT: 'Mathematics', ENG: 'Engineering', SOC: 'Social Sciences', PSY: 'Psychology', OTH: 'Other Science' },
  C: { UXD: 'UX Design', GRD: 'Graphic Design', WRT: 'Writing', PHO: 'Photography', VID: 'Video Production', AUD: 'Audio Production', ART: 'Fine Art', ANI: 'Animation', TYP: 'Typography', OTH: 'Other Creative' },
};
