// ============================================================
// Migration: 011_add_subcategory
// Adds subcategory_label column for semantic subcategory grouping
// ============================================================

import type { Migration } from './types.js';

const migration: Migration = {
  name: '011_add_subcategory',
  up(db) {
    // Add human-readable subcategory label column
    // Generated by AI, sits between category and item in the hierarchy
    db.exec(`ALTER TABLE nodes ADD COLUMN subcategory_label TEXT;`);

    // Composite index for category + subcategory filtering and tree building
    db.exec(`
      CREATE INDEX idx_nodes_category_subcat
        ON nodes(category_code, subcategory_label)
        WHERE is_deleted = 0;
    `);
  },
  down(db) {
    db.exec(`DROP INDEX IF EXISTS idx_nodes_category_subcat;`);
    // SQLite doesn't support DROP COLUMN — column remains but is ignored
  },
};

export default migration;
